### ISSUE TITLE
[BUG]: Deno.args not iterable error.

### ISSUE THREAD

**Issue by imjamesb** [josh-hemphill/azure-msal-deno#1]
### Prerequisites

  * [*] Reproduced the problem in a sandbox or repo: <https://codepen.io>
  * [*] Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+repo%3Ajosh-hemphill/azure-msal-deno>

### Description

```
TypeError: Deno.args is not iterable
at https://deno.land/x/azure_msal_deno@v1.1.0/dist/index.js:4926:13
```

### Steps to Reproduce

Importing the module.

**Comment by josh-hemphill** [comment]
What version of Deno are you using? I can't seem to reproduce this. `Deno.args` seems to always be an iterable empty array if no args are passed.

**Comment by imjamesb** [comment]
1.14.3---- On Mon, 11 Oct 2021 19:12:33 +0200  ***@***.***> wrote ---- 
What version of Deno are you using? I can't seem to reproduce this. Deno.args seems to always be an iterable empty array if no args are passed.

**Comment by josh-hemphill** [comment]
It looks like you replied to this thread (the last notification) via email, without adding anything. Did you mean to post something?

**Comment by imjamesb** [comment]
Im on 1.14.3

**Comment by josh-hemphill** [comment]
Are you using in the new deno deploy or something? I'm using the same version and can't replicate it.
